stable_rust: &stable_rust
  docker:
    - image: circleci/python:latest

      environment:
        RUST_VERSION: 1.24.1

  steps:
    - checkout
    - setup_remote_docker

    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - run: >-
        docker build
        --build-arg RUST_VERSION=$RUST_VERSION
        -t $DOCKER_USER/rust-$CIRCLE_JOB:rust-$RUST_VERSION
        rust-$CIRCLE_JOB

    - run: docker push $DOCKER_USER/rust-$CIRCLE_JOB:rust-$RUST_VERSION


nightly_rust: &nightly_rust
    docker:
      - image: circleci/python:latest

        environment:
          RUST_VERSION: nightly-2018-03-07
          CLIPPY_VERSION: 0.0.187

    steps:
      - checkout
      - setup_remote_docker

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: >-
          docker build
          --build-arg RUST_VERSION=$RUST_VERSION
          --build-arg CLIPPY_VERSION=$CLIPPY_VERSION
          -t $DOCKER_USER/rust-$CIRCLE_JOB:rust-$RUST_VERSION
          rust-$CIRCLE_JOB

      - run: docker push $DOCKER_USER/rust-$CIRCLE_JOB:rust-$RUST_VERSION


version: 2

jobs:
  aarch64:
    <<: *stable_rust
  rpi:
    <<: *stable_rust
  armv7hf:
    <<: *stable_rust
  i386:
    <<: *stable_rust
  amd64:
    <<: *stable_rust
  test-deploy:
    <<: *nightly_rust
  test-deploy-systemd:
    <<: *nightly_rust


workflows:
  version: 2
  build:
    jobs:
      - test-deploy
      - test-deploy-systemd
      - aarch64
      - rpi
      - armv7hf
      - i386
      - amd64
